#!/bin/sh
# ./test pas [b4 b4i bios pre b4s b4h b4a]
set -eu
ROOT=$(CDPATH= cd "$(dirname "$0")/.." && pwd)
. "$ROOT/imp/common.sh"
cd "$ROOT"
ensure_tanco

if [ $# -eq 0 ]; then
  set -- b4 b4i bios pre b4s b4h b4a
fi

b4i_built=
need_b4i() {
  if [ -z "$b4i_built" ]; then
    (cd "$ROOT/imp/pas" && make b4i)
    b4i_built=1
  fi
}

for suite in "$@"; do
  case $suite in
    b4)
      need_b4i
      tanco_run b4-tests.org -- imp/pas/b4i
      ;;
    b4i)
      need_b4i
      tanco_run b4i-tests.org -- imp/pas/b4i
      ;;
    bios)
      need_b4i
      tanco_run bios-tests.org -- imp/pas/b4i -a b4a/bios.b4a
      ;;
    pre)
      need_b4i
      tanco_run pre-tests.org -- imp/pas/b4i -a b4a/pre.b4a
      ;;
    b4s)
      need_b4i
      tanco_run b4s-tests.org -- imp/pas/b4i -a b4a/bios.b4a -a b4a/pre.b4a -a b4a/b4s.b4a
      ;;
    b4h)
      (cd "$ROOT/imp/pas" && make b4h)
      tanco_run b4h-tests.org -- imp/pas/b4h
      ;;
    b4a)
      (cd "$ROOT/imp/pas" && make b4 b4a)
      imp/pas/b4a b4a/b4i.b4a b4i.b4x
      tanco_run b4-tests.org -c "imp/pas/b4 -l b4i.b4x"
      ;;
    *)
      echo "pas: unknown suite '$suite'" >&2
      echo "suites: b4 b4i bios pre b4s b4h b4a" >&2
      exit 2
      ;;
  esac
done
