#+title: b4 vm/debugger test suite
#+tanco-format: 0.2

* About this file
This is a suite of acceptance tests for the B4 virtual machine.
There are B4 implementations in multiple languages, so this file
helps to make sure they are all compatible and follow the spec.

* How to read the tests

The important lines in this file are the code sections.

Lines starting with =>= are /input/ to the program.

Lines without =>= are the expected outputs.

* Running the tests

The tests in this file are run using Python and require [[https://github.com/tangentcode/tanco][tanco]].

#+begin_src bash
pip install tanco
#+end_src

To run, you supply tanco with a test file (like this one) using
the =-t= parameter, and a command to run with the =-c= parameter.

The command is generally an implementation of [[docs/b4i.org][b4i]] (the b4
interactive assembler) in some host language.

See the =test-b4-*= scripts in this repository for examples.

* debugger interface
** =%q= : quit

The =%q= command instructs b4 to quit.

b4 should not produce any output unless explicitly instructed to do so.

#+name: io.%q
#+begin_src b4a
> %q
#+end_src

** TEST io.?d : =?d= : query the data stack
#+begin_src b4a
> ?d %q
ds: [] # should be an empty array
#+end_src

** TODO test the display of negative numbers

which of these should it be?

: ds: [CC00BBAA]
: ds: [-33FF4456]


** TEST io.?c : =?c= : query the call stack
#+begin_src b4a
> ?c %q
cs: [] # should be an empty array
#+end_src

** TEST io.hex : hex numbers are pushed to the data stack
# Original headline: push a hex number to the stack
#+begin_src b4a
> FF CC ?d %q
ds: [FF CC]
#+end_src

it should print in hex
** TEST io.ascii : ascii syntax
# Original headline: push an ASCII character onto the stack
#+begin_src b4a
> 'a 'A ' ?d %q
ds: [61 41 20]
#+end_src

note lack of a second space after the '
it should print in hex
** TEST io.ctrl : control characters
# Original headline: push control character addresses to stack
#+begin_src b4a
> `@ `A `B `C `X `Y `Z ?d %q
ds: [0 4 8 C 60 64 68]
#+end_src

the 32 ASCII control characters act as a dictionary.
(^@ is written 00 and is a no-op)
^@ calls the word whose address is at address 0000
  (but the actual code emitted is =lb 00 cl= op, as bytecode 0 is a null op)
^A calls the word whose address is at address (4 * 1 = 0004)
^X calls the word whose address is at address (4 * (ord('X') - ord('@')) = 0x60)
But if we want a handy way to refer to the address, we use `X

#+name: io.ctrl2
#+begin_src b4a
> `[ `\ `] `^ `_ ?d %q
ds: [6C 70 74 78 7C]
= non-alphabetic control characters
: there are 5 control characters after ^Z that use punctuation.
#+end_src
* TEST op.c : constant ops
#+begin_src b4a
  > c0 c1 c2 n1 c4 ?d %q
  ds: [0 1 2 -1 4]
#+end_src

These ops push small constants onto =ds=.

* ALU / stack operations
** TEST op.ad : ad: adds the top two items on the stack
# Original headline: =ad= op
#+begin_src b4a
> 01 02 ad ?d %q
ds: [3]
#+end_src

The result is pushed back to the stack.
** TEST op.ml : =ml= op
#+begin_src b4a
> 03 03 ml ?d %q
ds: [9]
#+end_src
** TEST io.math : =sb= op
#+begin_src b4a
> 0A 05 sb ?d %q
ds: [5]
#+end_src

** TEST math.dv : =dv= op
#+begin_src b4a
> 0A 05 dv ?d %q
ds: [2]
#+end_src
** TEST math.md : =md= op
#+begin_src b4a
> 0A 05 md ?d
ds: [0]
> zp 0A 03 md ?d %q
ds: [1]
#+end_src
** TEST math.sh : sh : shift
# Original headline: =sh= op
#+begin_src b4a
  > : c4 c1 sh rt
  >   %s %s %s ?d
  ds: [8]
#+end_src

The 'sh' op shifts the bits of NOS by the amount in TOS.

#+name: math.shr
#+begin_src b4a
  > : c4 n1 sh rt
  >   %s %s %s ?d
  ds: [2]
  = sh : shift right
  : When the TOS is negative, we shift the NOS to the right.
#+end_src

** TEST math.an : =an= op
#+begin_src b4a
> 12 35 an ?d %q
ds: [10]
#+end_src

** TEST math.or : =or= op
#+begin_src b4a
> 12 35 or ?d %q
ds: [37]
#+end_src

** TEST math.xr : =xr= op
#+begin_src b4a
> 12 35 xr ?d %q
ds: [27]
#+end_src

** TEST math.nt : =nt= op
#+begin_src b4a
> 12 nt ?d %q
ds: [-13]
#+end_src

** TEST math.eq : =eq= op
#+begin_src b4a
> AA BB eq CC CC eq ?d %q
ds: [0 -1]
#+end_src

** TEST op.lt : =lt= op
#+begin_src b4a
> AA BB lt DD CC lt EE EE lt ?d %q
ds: [-1 0 0]
#+end_src

** TEST op.du : =du= op
#+begin_src b4a
> 0A du ?d %q
ds: [A A]
#+end_src b4a
** TEST op.zp : =zp= op
#+begin_src b4a
> 0A ?d zp ?d %q
ds: [A]
ds: []
#+end_src
** TEST io.sw : =sw= op
#+begin_src b4a
> 0A 0B sw ?d %q
ds: [B A]
#+end_src
** TEST op.ov : =ov= op
#+begin_src b4a
> 0A 0B ov ?d %q
ds: [A B A]
#+end_src
** TEST op.cd-dc : =cd= and =dc= ops
#+begin_src b4a
> 0A dc ?d ?c
ds: []
cs: [A]
> cd ?d ?c %q
ds: [A]
cs: []
#+end_src

* batch memory access from debugger
** TEST b4i.mem-show : =?<addr>= inspect memory at address
#+begin_src b4a
> ?100 %q
.. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. # 16 0 bytes
#+end_src
** TEST b4i.mem-write : =:<addr>= assemble to memory at address
#+begin_src b4a
> ?100
.. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..
> :100 00 AA BB CC
> ?100 %q
.. AA BB CC .. .. .. .. .. .. .. .. .. .. .. ..
#+end_src


* memory operations

** TODO test that %C clears memory and stacks
** TEST io.wi : =wi= : write int32 to address

#+begin_src b4a
> %C
> AABBCCDD 0100 wi
> ?100 %q
DD CC BB AA .. .. .. .. .. .. .. .. .. .. .. .. # 16 0 bytes
#+end_src

** TEST io.wb : =wb= : write byte to address

#+begin_src b4a
> %C
> AABBCCDD 0100 wb
> ?100 %q
DD .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. # 16 0 bytes
#+end_src

** TEST op.ri : =ri= : read int32 from address

#+begin_src b4a
> :100 AA BB CC 00
> ?100
AA BB CC .. .. .. .. .. .. .. .. .. .. .. .. ..
> 0100 ri ?d %q
ds: [CCBBAA]
#+end_src
** TEST op.rb : =rb= : read byte from address

#+begin_src b4a
> :100 AA BB 00 77
> ?100
AA BB .. +W .. .. .. .. .. .. .. .. .. .. .. ..
> 0100 ri ?d %q
ds: [7700BBAA]
#+end_src

** TEST op.rs : =rs= : read signed byte from address
#+begin_src b4a
  > :A 7F :B FF
  > :R @A rs @B rs rt
  > ^R ?d %q
  ds: [7F -1]
#+end_src




* register ops

** =@R= and =!R= : read and write registers
*** TEST op.rr-wr.runtime : assembler:
#+begin_src b4a
  > :100 lb 12 !X @X c1 +X @X
  > %s ?d
  ds: [12]
  > %s ?d ?X  # !X
  ds: []
  00000012
  > %s ?d ?X  # @X
  ds: [12]
  00000012
  > %s %s ?d ?X  # c1 +X
  ds: [12 12]
  00000013
  > %s ?d ?X # @X
  ds: [12 12 13]
  00000013
  > %q
#+end_src

*** TEST op.rr-wr : interactively:
#+begin_src b4a
> 12345678 !X ?d
ds: []
> @X ?d %q
ds: [12345678]
#+end_src

** =+R= : stream via register

The =+= ops take a value off the stack and add it to a register,
pushing the value of the register *before* the addition onto the data stack.
You can use this to treat the register as a cursor through a string or array of values.

#+name: op.plus-x
#+begin_src b4a
> 11223344 !X
> 04 +X 02 +X @X ?d %q
ds: [11223344 11223348 1122334A]
#+end_src


* debugger commands: stepping
** TEST dbg.?i : =?i= : query instruction pointer

#+begin_src b4a
> ?i %q
ip: 100
#+end_src
** TEST dbg.%s : =%s= : step command

#+begin_src b4a
> ?i %s ?i %q
ip: 100
ip: 101
#+end_src

* sequence ops
** TODO =..= (zero) is no-op
** load ops

The following operations load values into ram from the bytes following the
instruction pointer.

*** TEST op.li : =li= op
#+begin_src b4a
  > :100 li 44 33 22 11 li FF FF FF FF rt
  > %s %s ?d %q
  ds: [11223344 -1]
#+end_src
*** TEST op.seq.lb : lb: load byte
# Original headline: =lb= op
#+begin_src b4a
> :100 lb AB
> ?100
lb AB .. .. .. .. .. .. .. .. .. .. .. .. .. ..
> ?d
ds: [] # it should not be on the stack YET
> %s ?d ?i %q
ds: [AB]
ip: 102
#+end_src

lb loads a byte from memory at runtime.
we never needed it before because our debug shell
is pushing numbers directly to the stack
*** TEST op.lb : =lb= : load a byte
#+begin_src b4a
  > :L lb 7F lb FF rt
  > ^L ?d %q
  ds: [7F FF]
#+end_src
*** TEST op.ls : =ls= : load signed byte
#+begin_src b4a
  > :L ls 7F ls FF rt
  > ^L ?d %q
  ds: [7F -1]
#+end_src

** =hp= : hop
Hop is a small relative jump. It takes a signed 8-bit int as a parameter, and can thus move the instruction pointer forward up to 127 bytes, or backwards up to 128 bytes.

*** TEST op.hp.forward : forward
#+begin_src b4a
> :100 hp 05
> ?i %s ?i %q
ip: 100
ip: 105
#+end_src
*** TEST op.hp.forward-max : forward max
#+begin_src b4a
> :100 hp 7F
> %s ?i %q
ip: 17F
#+end_src
*** TEST op.hp.forward-wrap : forward wrap
#+begin_src b4a
> :100 hp 80
> %s ?i %q
ip: 100
#+end_src

*** TEST op.hp.backward : backward
#+begin_src b4a
> :100 .. .. .. hp -3
> %s %s %s ?i %s ?i %q
ip: 103
ip: 100
#+end_src
*** TEST op.hp.backward-oob : backward (and out of bounds)
#+begin_src b4a
> :100 hp -5
> %s ?i %q
ip: 100
#+end_src
*** TEST op.hp.zero : zero?
#+begin_src b4a
> :100 hp 00
> %s ?i %q
ip: 100
#+end_src
** =h0= hop if 0

=h0= is the same as =hp= but conditional.

It pops a value off the data stack, and only hops if the value is 0.

*** TEST op.h0.when0 : when 0
#+begin_src b4a
> :100 h0 23
> 00 %s ?i %q
ip: 123
#+end_src
*** TEST op.h0.when1 : when 1
#+begin_src b4a
> :100 h0 23
> 01 %s ?i %q
ip: 102
#+end_src

** TEST op.jm : =jm= jump

#+begin_src b4a
> :100 jm 78 56 34 12
> %s ?i %q
ip: 12345678
#+end_src

** =cl= call

=cl= is the same as =jm= but also pushes a return address to the control stack.

Note that the instruction pointer is incremented by 5 first, to skip over the =cl= op itself, plus its 4-byte argument.

#+name: op.cl
#+begin_src b4a
> :100 cl 78 56 34 12
> %s ?i ?c %q
ip: 12345678
cs: [105]
#+end_src

** =rt= return

In general, =rt= is used to return control from a called function.

The actual mechanism is a jump to an address popped from the control stack.

To simplify this test, we simply push the address we want to the control stack ourselves.

#+name: op.rt
#+begin_src b4a
> :100 rt
> 1234 dc ?i ?c %s ?i ?c %q
ip: 100
cs: [1234]
ip: 1234
cs: []
#+end_src

** =rt= dynamic call caveat

Here's a small catch for the "dynamic call" technique used in the previous test.

It =only= comes into play when using the "calculator mode".

Note that in the previous test, we used =%s= to trigger a step. This
reads an instruction from RAM[ip] and then causes the instruction pointer to increment.

If we had simply invoked =rt= directly using the "calculator", no "step" has occurred, and so the address would be off by one.

In general, it probably just doesn't make sense to use control flow ops from the "calculator" outside of testing.

#+name: op.rt.b4i
#+begin_src b4a
> 1234 dc ?i ?c rt ?i ?c %q
ip: 100
cs: [1234]
ip: 1233
cs: []
#+end_src

** =nx= next

This is probably the most complicated operation.

It's intended for loops where you do something a fixed number of times.

An integer counter is stored on the control stack. Every time =nx= is run,
the counter is decremented. A hop is triggered when the result is
/not/ zero, so that the loop continues until the countdown reaches 0.

On the step where it does reach zero, the counter is dropped.

In this test, we loop back to the starting address twice, and then proceed.

#+name: op.nx
#+begin_src b4a
> :100 nx 00
> 2 dc
> ?c ?i
cs: [2]
ip: 100
> %s ?c ?i
cs: [1]
ip: 100
> %s ?c ?i
cs: []
ip: 102
> %s ?c ?i
cs: []
ip: 103
> %q
#+end_src

* =io= op

** 'e for emit

This should emit a single character.

While running in the b4i interpreter, it should buffer the output until the end of line is received.

#+name: op.io.e
#+begin_src b4a
> 'h 'e io 'i 'e io %q
hi
#+end_src


* TEST b4a.db : =db= opcode: pause for debugger
#+begin_src b4a
  > :A c0 c1 db c2 c4 rt
  > ?i
  ip: 100
  > ^A ?d ?i
  ds: [0 1]
  ip: 103
  > %s %s ?d
  ds: [0 1 2 4]
#+end_src

=db= is an opcode that causes the system to pause for inspection.


* TEST b4a.%g : debugger command: =\g= (go) to resume execution
#+begin_src b4a
  > :A c0 c1 db c2 c4 rt
  > ?i
  ip: 100
  > ^A ?d ?i
  ds: [0 1]
  ip: 103
  > \g ?d
  ds: [0 1 2 4]
#+end_src

=\g= resumes operation.


* debugger commands: registers

** TEST ctrl.e : =:R= : point register at current assembly address
#+begin_src b4a
  > :E lb 'e io rt
  > 'o ^E 'k ^E
  ok
  > %q
#+end_src

** TEST here : =?R= : show contents of register R
#+begin_src b4a
  > ?E                # by default, most registers are blank
  00000000
  > ?_                # but "here" pointer is set to $100=256
  00000100
  > :E lb 'e io rt    # assemble "emit"
  > ?E                # now ^E should be assigned
  00000100
  > ?_ %q             # and ^_ should reflect the 4 bytes we assembled
  00000104
#+end_src

* assembler macros
** TEST b4a.getset : =@lbl= and =!lbl= : get/set address (b4a)
#+begin_src b4a
  > :int 04 03 02 01
  > :get @int rt
  > :set !int rt
  > get ?d
  ds: [1020304]
  > 5 set get ?d %q
  ds: [1020304 5]
#+end_src

These are macros. They emit a =li= op, followed by the address, then either =ri= or =wi=.

** string literals
*** TEST b4a.string.raw : ="abc"= : raw string
#+begin_src b4a
> :100 "abc def"
> ?100 %q
+A +B +C @@ +D +E +F .. .. .. .. .. .. .. .. ..
#+end_src

*** TEST b4a.string.len-prefixed : =."abc"= : length-prefixed string
#+begin_src b4a
> :100 ."abc def"
> ?100 %q
^G +A +B +C @@ +D +E +F .. .. .. .. .. .. .. ..
#+end_src

** TEST b4a.fwd : Using =>= for forward references
#+begin_src b4a
  > :A cl >foo rt
  > \f
  0101>foo
  > :foo c2 n1 rt
  > \f
  > ^A ?d %q
  ds: [2 -1]
#+end_src

Inside the assembler, you can use the =>= prefix to indicate a word
that is to be defined later. Note that unlike a bare word, this does
not assemble an implicit =cl= so you must write it manually.

Meanwhile, the =\f= command can be used to inspect forward references
that have not yet been filled in.

** TEST b4a.u32 : =$= for u32 hex values
#+begin_src b4a
> :100 lb C0 li $AA .. lb C1 li AA .. .. .. ..
> ?100
lb c0 li AA .. .. .. .. lb c1 li AA .. .. .. ..
> : lb C2 li $01020304 rt
> ?110
lb C2 li ^D ^C ^B ^A rt .. .. .. .. .. .. .. ..
#+end_src

Using =$= in front of a number makrs


* TODO [0/2] system ops (how to test these?)
** TODO =hl=  halts the virtual machine
