#+TITLE: License Information for B4 Language Project
#+AUTHOR: Michal J Wallace
#+DATE: 2012/08/14

* OVERVIEW All code is MIT-license compatible

This system incorporates code from a variety of open source projects.

All of these projects are open source and released under extremely liberal and inter-compatible licenses.

For the sake of simplicity, you should be able to treat everything here as if it were released under the MIT license. Which basically
means: *you can do pretty much anything with this code, so long as you don't claim it as your own or hold the authors liable for damages.*

The following two tables summarize

For detailed author and copyright information, consult the headers at the start of each file.


* TABLE licenses used by code in this project

| license   | used by code in:      |
|-----------+-----------------------|
| [[http://en.wikipedia.org/wiki/ISC_license][ISC]]       | ngaro.js              |
| [[http://en.wikipedia.org/wiki/MIT_License][MIT]]       | ngterm.js, pl/0 tools |
| [[http://unlicense.org/][UNLICENSE]] |                       |
|           |                       |

* TABLE source projects and their licenses

| project             | maintainer            | repo    | license | used by (or incorporated into): |
|---------------------+-----------------------+---------+---------+---------------------------------|
| rx-core             | Charles Childers      | [[https://launchpad.net/retro-language/][lp]] , [[https://github.com/crcx/retro-language][gh]] |         |                                 |
| [[http://256.io/escapes.js/][escapes.js]]          | Ori Livneh            | [[https://github.com/atdt/escapes.js/][gh]]      | [[https://github.com/atdt/escapes.js/blob/master/LICENSE][MIT/GPL]] | incorporated into ngterm.js     |
| [[http://www.oriontransfer.co.nz/learn/pl0-language-tools/index][pl/0 language tools]] | Samuel G. D. Williams | [[https://github.com/oriontransfer/pl0-language-tools][gh]]      | [[https://github.com/oriontransfer/PL0-Language-Tools/blob/master/README.md][MIT]]     |                                 |
|                     |                       |         |         |                                 |


* SECTION actual license texts

** ISC License

Copyright (c) <year> <copyright holders>

Permission to use, copy, modify, and/or distribute this software for
any purpose with or without fee is hereby granted, provided that the
above copyright notice and this permission notice appear in all
copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
PERFORMANCE OF THIS SOFTWARE.

** MIT License

Copyright (c) <year> <copyright holders>

Permission is hereby granted, free of charge, to any person obtaining
a copy of this software and associated documentation files (the
"Software"), to deal in the Software without restriction, including
without limitation the rights to use, copy, modify, merge, publish,
distribute, sublicense, and/or sell copies of the Software, and to
permit persons to whom the Software is furnished to do so, subject to
the following conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

** Unlicense

This is free and unencumbered software released into the public domain.

Anyone is free to copy, modify, publish, use, compile, sell, or
distribute this software, either in source code form or as a compiled
binary, for any purpose, commercial or non-commercial, and by any
means.

In jurisdictions that recognize copyright laws, the author or authors
of this software dedicate any and all copyright interest in the
software to the public domain. We make this dedication for the benefit
of the public at large and to the detriment of our heirs and
successors. We intend this dedication to be an overt act of
relinquishment in perpetuity of all present and future rights to this
software under copyright law.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.

For more information, please refer to <http://unlicense.org/>

