#!/bin/sh
export VER="/d/ver"
export TEST_PLAN="$VER/b4/b4-tests.org"

# godot outputs a version header and blank line that cannot be suppressed:
# (at least not without suppressing ALL output)
export SKIP_LINES=2

# godot 4.2.1 also won't read "stdin" lines from a pipe on windows,
# so we write the commands to a file and then tell
export INPUT_PATH=../b4-gd/input.txt

# TODO: actually use tanco
export TANCO="python $VER/learntris/testris.py"

export GODOT="d:/ver/b4-gd/Godot_v4.1.2-stable_win64_console.exe"

$TANCO $GODOT --path ../b4-gd --headless --script cli.gd -- input.txt
