#!/bin/sh
# godot outputs a version header and blank line that cannot be suppressed:
# (at least not without suppressing ALL output)
export SKIP_LINES=2

# godot 4.2.1 also won't read "stdin" lines from a pipe on windows,
# so we write the commands to a file and then tell
export INPUT_PATH=../b4-gd/input.txt

# Determine GODOT path: Use $GODOT from environment if set, otherwise use default
DEFAULT_GODOT="~/Downloads/Godot_v4.3-stable_win64.exe/Godot_v4.3-stable_win64_console.exe"
if [ -n "$GODOT" ]; then
  GODOT_PATH="$GODOT"
else
  GODOT_PATH="$DEFAULT_GODOT"
fi
export GODOT="$GODOT_PATH"

# Use tanco to run tests
tanco run --tests b4-tests.org "$GODOT" --path ../b4-gd --headless --script cli.gd -- input.txt
