#+title:  parity proofs

* definitions
:PROPERTIES:
:TS:       <2015-01-24 11:03PM>
:ID:       3bb8lxn0sqg0
:END:

** Bit Vector
*n*. A vector where each element is either 0 or 1.
#+begin_src J
  and =: *.
  all =: and/
  rank =: #@$
  isVec =: 1 = rank
  allBits =: 0 1 e.~ ,
  isBitV =: isVec and allBits
#+end_src

** =BV n= the set of all bit vectors of length =n=.
Can be generated by counting from =0= to =(2^n)-1= in binary.
#+begin_src J
  BV =: #:@i.
#+end_src

** Endomorphism
A mapping from a mathematical structure back to itself.

** =xors= xor scan
1. *v*. The process of inserting the xor verb between each item of each successive prefix of an array, and evaluating the results.
2. *n*. The result of this process.

#+begin_src J
  xors =: ~:/\
#+end_src

** =lp2= least power of 2 (of real number /n/)
*n*. The least power of 2 greater than or equal to =n=. If =p= is the base 2 logarithm of =n= rounded upward to the next whole number, then =lp2 n= is =2^p=.

#+begin_src J
  lp2 =: >. &. (2 & ^.)
  (,:lp2) i.16
0 1 2 3 4 5 6 7 8  9 10 11 12 13 14 15
0 1 2 4 4 8 8 8 8 16 16 16 16 16 16 16
#+end_src

* theorem: recursive xor scans on bit vectors of length =n= are cyclic with period =lp2 n=.
:PROPERTIES:
:TS:       <2015-01-24 11:28PM>
:ID:       bis4c2p0sqg0
:END:

** TODO 1. =(isBitV v)= → =(# xors v) = (# v)=
:PROPERTIES:
:TS:       <2015-01-24 11:48PM>
:ID:       jkscpzp0sqg0
:END:
(I'll need to formally define scans to prove this, then it's trivial because the length of the input is equal to the length of the output for /any/ scan.)

** TODO 2. =(isBitV v)= → =(isBitV xors v)=
Formally define xor for booleans, then:
This follows from lemma 1 and the definitions of =xors= and =xor=.

** 3. Thus =xors= is an endorphism on =BV n=.

** TODO 4. There are at exactly =2^n= distinct bit vectors of length =n=.
:PROPERTIES:
:TS:       <2015-01-24 11:58PM>
:ID:       k2b5ngq0sqg0
:END:
This should also be easy to prove, because =BV n= maps directly to the numbers =i.2^n= in binary.

** TODO 5. The period of any iterated endomorphism on =BV n= must be ≤ =2^n=.
:PROPERTIES:
:TS:       <2015-01-25 12:06AM>
:ID:       zuld5vq0sqg0
:END:
Keep applying a mapping from =BV n= to =BV n=, and eventually you will run out of distinct bit vectors.

Generalization: a similar thing can be said of any endmorphism on any finite set of objects.

** 6. Thus =xors= iterated on (=v e. BV n=) is cyclic with period ≤ =2^n=.
:PROPERTIES:
:TS:       <2015-01-25 12:52AM>
:ID:       plifvys0sqg0
:END:
