
constructor TDrive.init ( path : string );
begin
end;

procedure TDrive.wipe;
begin
end;

procedure TDrive.grow ( n : byte );
begin
end;

procedure TDrive.load ( i : integer; var b : TBlock );
begin
end;

procedure TDrive.save ( i : integer; var b : TBlock );
begin
end;

function TDrive.block_count : cardinal;
begin
end;

function TDrive.byte_count : cardinal;
begin
end;

destructor TDrive.done ( );
begin
end;
